flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- HUnit-1.3.0.0
- dotgen-0.4.2
- fgl-5.5.2.3
- fgl-visualize-0.1.0.1
- memoize-0.7
- parallel-3.2.0.6
- parsec-3.1.9
- text-1.2.1.3
- mtl-2.2.1
- setenv-0.1.1.3
- llvm-general-pure-3.5.1.0
- random-1.1
- time-1.5.0.1
- setenv-0.1.1.3
- unix-2.7.1.0
resolver: ghc-7.10.3
